# docker-compose is the top layer for how to run the Dockerfile
version: '3.10'

services:
  app:
    build:
      context: .
      # ports: local machine port first, then container port
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"