# docker-compose is the top layer for how to run the Dockerfile
version: '3.10'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
      # ports: local machine port first, then container port
    ports:
      - "8000:8000"
      # volumes use to persist data, we want to persist the app dir
      # this creates a two way sync bw our
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
